name: 'fpl'
version: '1.0.0'
profile: 'fpl'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  fpl:

    staging:
      +schema: "staging"

    intermediate:
      +schema: "intermediate"

    marts:
      +schema: "mart"
