fpl:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('DB_HOST') }}"
      user: "{{ env_var('DB_USER') }}"
      password: "{{ env_var('DB_PASS', '') }}"
      port: "{{ env_var('DB_PORT', 5432) | as_number }}"
      dbname: "{{ env_var('DB_NAME') }}"
      threads: 4

    staging:
      type: postgres
      host: "{{ env_var('STAGING_DB_HOST') }}"
      user: "{{ env_var('STAGING_DB_USER') }}"
      password: "{{ env_var('STAGING_DB_PASS') }}"
      port: "{{ env_var('STAGING_DB_PORT', 5432) | as_number }}"
      dbname: "{{ env_var('STAGING_DB_NAME') }}"
      threads: 4

    prod:
      type: postgres
      host: "{{ env_var('PROD_DB_HOST') }}"
      user: "{{ env_var('PROD_DB_USER') }}"
      password: "{{ env_var('PROD_DB_PASS') }}"
      port: "{{ env_var('PROD_DB_PORT', 5432) | as_number }}"
      dbname: "{{ env_var('PROD_DB_NAME') }}"
      threads: 4