CREATE SCHEMA IF NOT EXISTS ${RAW_STAGING_TMP_SCHEMA};
CREATE SCHEMA IF NOT EXISTS ${RAW_SCHEMA};
CREATE SCHEMA IF NOT EXISTS ${STAGING_SCHEMA};
CREATE SCHEMA IF NOT EXISTS ${INTERMEDIATE_SCHEMA};
CREATE SCHEMA IF NOT EXISTS ${MART_SCHEMA};
