version: 2

models:

  - name: stg_fixtures
    description: "Staging table for fixtures"
    columns:
      - name: fixture_id
        tests:
          - not_null
          - unique
      - name: gameweek_id
        tests:
          - not_null

  - name: stg_fixture_stats
    description: "Flattened fixture stats from raw.fixtures"
    columns:
      - name: fixture_id
        tests:
          - not_null
      - name: stat_identifier
        tests:
          - not_null
      - name: team_type
      - name: player_id
        tests:
          - not_null
      - name: stat_value

  - name: stg_gameweeks
    description: "Staged gameweek (events) from bootstrap_static"
    columns:
      - name: gameweek_id
        tests: [unique, not_null]

      - name: gameweek_name
        tests: [not_null]

      - name: deadline_time
        tests: [not_null]

      - name: average_entry_score
        tests: []

      - name: finished
        tests: []

      - name: data_checked
        tests: []

      - name: highest_score
        tests: []

      - name: deadline_time_epoch
        tests: []

      - name: is_previous
        tests: []

      - name: is_current
        tests: []

      - name: is_next
        tests: []

      - name: ranked_count
        tests: []

      - name: transfers_made
        tests: []

      - name: most_selected_player_id
        tests:
          - relationships:
              arguments:
                to: ref('stg_players')
                field: player_id

      - name: most_transferred_in_player_id
        tests:
          - relationships:
              arguments:
                to: ref('stg_players')
                field: player_id

      - name: most_captained_player_id
        tests:
          - relationships:
              arguments:
                to: ref('stg_players')
                field: player_id

      - name: most_vice_captained_player_id
        tests:
          - relationships:
              arguments:
                to: ref('stg_players')
                field: player_id

      - name: top_player_id
        tests:
          - relationships:
              arguments:
                to: ref('stg_players')
                field: player_id

      - name: top_element_info
        description: "jsonb; retained for audit"

      - name: chip_plays
        description: "jsonb array; retained for audit"

  - name: stg_gameweek_chip_plays
    description: "Normalized chip plays; one row per gameweek + chip"
    columns:
      - name: gameweek_id
        tests:
          - not_null
      - name: chip_name
        tests:
          - not_null
      - name: num_played
        tests:
          - not_null
    # tests:
    #   - dbt_utils.expression_is_true:
    #       expression: "num_played >= 0"
  
  - name: stg_player_positions
    description: "Staged player positions (element_types)"
    columns:
      - name: player_position_id
        tests:
          - unique
          - not_null

      - name: player_position_singular_name
        tests:
          - not_null

      - name: player_position_singular_name_short
        tests:
          - not_null

      - name: player_position_plural_name
        tests: []

      - name: player_position_plural_name_short
        tests: []

      - name: squad_select
        tests:
          - not_null

      - name: squad_min_select
        tests: []

      - name: squad_max_select
        tests: []

      - name: squad_min_play
        tests:
          - not_null

      - name: squad_max_play
        tests:
          - not_null

      - name: element_count
        tests:
          - not_null

  - name: stg_teams
    description: "Staged teams from bootstrap_static"
    columns:
      - name: team_id
        tests:
          - unique
          - not_null

      - name: code
        tests:
          - not_null

      - name: team_name
        tests:
          - not_null

      - name: team_short_name
        tests:
          - not_null

      - name: team_position
        tests: []  # nullable at season start

      - name: played
        tests:
          - not_null

      - name: wins
        tests:
          - not_null

      - name: draws
        tests:
          - not_null

      - name: losses
        tests:
          - not_null

      - name: points
        tests:
          - not_null

      - name: strength
        tests:
          - not_null

      - name: pulse_id
        tests:
          - not_null

      - name: strength_overall_home
        tests: []

      - name: strength_overall_away
        tests: []

      - name: strength_attack_home
        tests: []

      - name: strength_attack_away
        tests: []

      - name: strength_defence_home
        tests: []

      - name: strength_defence_away
        tests: []

  - name: stg_players
    description: "Staged players (elements) from bootstrap_static"
    columns:
      - name: player_id
        description: "natural key for player"
        tests:
          - unique
          - not_null

      - name: player_web_name
        description: "display name"
        tests:
          - not_null

      - name: team_id
        description: "FK to teams"
        tests:
          - not_null

      - name: position_id
        description: "FK to player positions / element_type"
        tests:
          - not_null

      - name: now_cost
        description: "current cost (stored as now_cost/10)"
        tests:
          - not_null

      - name: total_points
        description: "cumulative points"
        tests:
          - not_null

      - name: minutes
        description: "minutes played"
        tests: []

      - name: starts
        tests: []

      - name: goals_scored
        tests: []

      - name: assists
        tests: []

      - name: clean_sheets
        tests: []

      - name: bps
        tests: []

      - name: bonus
        tests: []

      - name: selected_by_percent
        tests: []

      - name: transfers_in
        tests: []

      - name: transfers_out
        tests: []

      - name: now_cost_rank
        tests: []

      - name: news_added
        tests: []

      - name: in_dreamteam
        tests: []

      - name: selected_rank
        tests: []

      - name: selected_rank_type
        tests: []

      - name: ep_next
        tests: []

      - name: ep_this
        tests: []

      - name: influence
        tests: []

      - name: ict_index
        tests: []

      - name: expected_goals
        tests: []

      - name: expected_assists
        tests: []

      - name: expected_goals_conceded
        tests: []

      - name: starts_per_90
        tests: []

      - name: saves
        tests: []

      - name: saves_per_90
        tests: []

      - name: news
        tests: []