version: 2

models:
  - name: stg_fixtures
    description: "Staging table for fixtures"
    columns:
      - name: fixture_id
        tests:
          - not_null
          - unique
      - name: gameweek_id
        tests:
          - not_null
  - name: stg_fixture_stats
    description: "Flattened fixture stats from raw.fixtures"
    columns:
      - name: fixture_id
        tests:
          - not_null
      - name: stat_identifier
        tests:
          - not_null
      - name: team_type
      - name: player_id
        tests:
          - not_null
      - name: stat_value